### ISSUE TITLE
 Unknown/unsupported storage engine: InnoDB

### ISSUE THREAD

**Issue by angelxmoreno** [yobasystems/alpine-mariadb#16]
Getting an error ` Unknown/unsupported storage engine: InnoDB`. This is my compose file snippet
```
mysql:
    container_name: ${APP_NAME}-mysql
    image: yobasystems/alpine-mariadb
    ports:
    - 8806:3306/tcp
    volumes:
    - './docker/data/mysql:/var/lib/mysql'
    environment:
    - MYSQL_ROOT_PASSWORD=${APP_NAME}
    - MYSQL_DATABASE=${APP_NAME}
    - MYSQL_USER=${APP_NAME}
    - MYSQL_PASSWORD=${APP_NAME}
```
