### ISSUE TITLE
Fresh run creates too many users

### ISSUE THREAD

**Issue by demyxco** [yobasystems/alpine-mariadb#26]
![](https://i.imgur.com/fctqjI7.png)

```
mariadb:
  container_name: mariadb
  restart: unless-stopped
  image: yobasystems/alpine-mariadb
  volumes:
    - ./mariadb:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  networks:
    - proxy
  labels:
    - "traefik.enable=false"
```
