### ISSUE TITLE
Docker Secrets

### ISSUE THREAD

**Issue by RussellNS** [yobasystems/alpine-mariadb#32]
There is no support for 'Docker Secrets' in this image.  The setup for Docker Secrets may be different between Docker Swarm and Docker Compose.  However, the end result is the same.  A plain text file will end up inside the container at '/run/secrets/' where each file will contain 1 secret (account name, password, etc.).  The contents of this plain text file is then available to the entrypoint of the container.

The current build of this container uses these example environment variables:

```
    MYSQL_ROOT_PASSWORD: hguyFtgfR4r9R4r76
    MYSQL_DATABASE: wordpressdb
    MYSQL_USER: wordpressuser
    MYSQL_PASSWORD: hguyFt6S95dgfR4ryb
    MYSQL_CHARSET: utf8mb4
    MYSQL_COLLATION: utf8mb4_general_ci
```

The code that handles the environment variables appears to be in 'run.sh':

```
    if [ "$MYSQL_ROOT_PASSWORD" = "" ]; then
        MYSQL_ROOT_PASSWORD=`pwgen 16 1`
        echo "[i] MySQL root Password: $MYSQL_ROOT_PASSWORD"
    fi

    MYSQL_DATABASE=${MYSQL_DATABASE:-""}
    MYSQL_USER=${MYSQL_USER:-""}
    MYSQL_PASSWORD=${MYSQL_PASSWORD:-""}

```
The normal construct for using Docker Secrets is to use the same environment variable name(s), but with '_FILE' appended, thereby allowing the use of both the original environment variable or the path that contains the 'secret' value.  The filename used for the secret is made up entirely by the user, but is usually something meaningful.  Example:

```
    MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_pass
    MYSQL_DATABASE_FILE: /run/secrets/db_name
    MYSQL_USER_FILE: /run/secrets/db_admin_name
    MYSQL_PASSWORD_FILE: /run/secrets/db_admin_pass
    MYSQL_CHARSET: /run/secrets/db_charset
    MYSQL_COLLATION: /run/secrets/db_collation

```
Would it be possible to change this code to use docker secrets (i.e. parse the specified file in /run/secrets) for the information for these variables?

Proposed Example 'docker-compose.yml':
```
  services:
    mariadb:
      image: yobasystems/alpine-mariadb
      environment:
        MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_pass
        MYSQL_DATABASE_FILE: /run/secrets/db_name
        MYSQL_USER_FILE: /run/secrets/db_admin_name
        MYSQL_PASSWORD_FILE: /run/secrets/db_admin_pass
        MYSQL_CHARSET_FILE: /run/secrets/db_charset
        MYSQL_COLLATION_FILE: /run/secrets/db_collation

      secrets:
        - db_root_pass
        - db_name
        - db_admin_name
        - db_admin_pass
        - db_charset
        - db_collation
      expose:
        - "3306"
      volumes:
        - /data/example/mysql:/var/lib/mysql
      restart: always

  secrets:
    db_root_pass:
      file: ./private/db_root_pass.txt
    db_name:
      file: ./private/db_name.txt
    db_admin_name:
      file: ./private/db_admin_name.txt
    db_admin_pass:
      file: ./private/db_admin_pass.txt
    db_charset:
      file: ./private/db_charset.txt
    db_collation:
      file: ./private/db_collation.txt

```
Proposed Example 'run.sh' Code Change:

    if [ "$MYSQL_ROOT_PASSWORD_FILE" = "" ]; then
        if [ "$MYSQL_ROOT_PASSWORD" = "" ]; then
            MYSQL_ROOT_PASSWORD=`pwgen 16 1`
            echo "[i] MySQL root Password: $MYSQL_ROOT_PASSWORD"
        fi
    else
        MYSQL_ROOT_PASSWORD=`cat $MYSQL_ROOT_PASSWORD_FILE`
        echo "[i] MySQL Root Password: $MYSQL_ROOT_PASSWORD"
    fi

    if [ "$MYSQL_DATABASE_FILE" = "" ]; then
        MYSQL_DATABASE=${MYSQL_DATABASE:-""}
    else
        MYSQL_DATABASE=`cat $MYSQL_DATABASE_FILE`
        echo "[i] MySQL Database Name: $MYSQL_DATABASE"
    fi

    if [ "$MYSQL_USER_FILE" = "" ]; then
        MYSQL_USER=${MYSQL_USER:-""}
    else
        MYSQL_USER=`cat $MYSQL_USER_FILE`
        echo "[i] MySQL User Name: $MYSQL_USER"
    fi

    if [ "$MYSQL_PASSWORD_FILE" = "" ]; then
        MYSQL_PASSWORD=${MYSQL_PASSWORD:-""}
    else
        MYSQL_PASSWORD=`cat $MYSQL_PASSWORD_FILE`
        echo "[i] MySQL User Password: $MYSQL_PASSWORD"
    fi

    if [ "$MYSQL_CHARSET_FILE" = "" ]; then
        MYSQL_CHARSET=${MYSQL_CHARSET:-""}
    else
        MYSQL_CHARSET=`cat $MYSQL_CHARSET_FILE`
        echo "[i] MySQL User Password: $MYSQL_CHARSET"
    fi

    if [ "$MYSQL_COLLATION_FILE" = "" ]; then
        MYSQL_COLLATION=${MYSQL_COLLATION:-""}
    else
        MYSQL_COLLATION=`cat $MYSQL_COLLATION_FILE`
        echo "[i] MySQL User Password: $MYSQL_COLLATION"
    fi

Assuming that each 'db_*.txt' file referenced above contained the original example values, then this would allow users to provide both of these with the same result:

```
    MYSQL_ROOT_PASSWORD: hguyFtgfR4r9R4r76
    MYSQL_DATABASE: wordpressdb
    MYSQL_USER: wordpressuser
    MYSQL_PASSWORD: hguyFt6S95dgfR4ryb
    MYSQL_CHARSET: utf8mb4
    MYSQL_COLLATION: utf8mb4_general_ci

```
and

```
    MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_pass
    MYSQL_DATABASE_FILE: /run/secrets/db_name
    MYSQL_USER_FILE: /run/secrets/db_admin_name
    MYSQL_PASSWORD_FILE: /run/secrets/db_admin_pass
    MYSQL_CHARSET_FILE: /run/secrets/db_charset
    MYSQL_COLLATION_FILE: /run/secrets/db_collation

```
Also, in the event that a user provides both secret and non-secret values for the same thing (i.e. MYSQL_USER and MYSQL_USER_FILE), the secret value will override the non-secret value in this proposed code change.

Thank you for your attention.

EDIT: Typos (x3).

**Comment by unixfox** [comment]
Up! This would be awesome for Docker Swarm clusters.

**Comment by dominictayloruk** [comment]
I'll have a look at this, i don't use swarm so will have to setup a test environment.

There is more info available [here](https://github.com/docker-library/rabbitmq/blob/master/3.8-rc/alpine/docker-entrypoint.sh) & [here](https://github.com/docker-library/mysql/blob/master/8.0/docker-entrypoint.sh).

Seems it's only relevant to swarm;

> **About secrets**
In terms of Docker Swarm services, a secret is a blob of data, such as a password, SSH private key, SSL certificate, or another piece of data that should not be transmitted over a network or stored unencrypted in a Dockerfile or in your application’s source code. In Docker 1.13 and higher, you can use Docker secrets to centrally manage this data and securely transmit it to only those containers that need access to it. Secrets are encrypted during transit and at rest in a Docker swarm. A given secret is only accessible to those services which have been granted explicit access to it, and only while those service tasks are running.

**Comment by am-mnandor** [comment]
Also relevant to k8s, I guess.

**Comment by dominictayloruk** [comment]
If this is relevant to k8s then it should be next on my list. I can test that i just don't use swarm.

**Comment by medilies** [comment]
Was this solved?
Because I did a secret test right now with mariadb service.
I opened bash inside a mariadb container
Did `#cat /run/secrets/mysecret` the value is correctly there
Did `# printenv` it showed
`MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysecret`
But connecting to the DB tells me access denied

**Comment by ahgraber** [comment]
@dominictayloruk 
if you add `01_secret-init.sh` (below) to `/scripts/pre-init.d`, it should automatically detect environmental variables named `var_name__FILE` (where the key is double-underscore-FILE).  Due to the nature of posix sh, we have to use an 'eval' hack for indirect variable reference.  If you install bash and update `run.sh` and `01_secret-init.sh` to use bash, we can replace `eval SECRETFILE="\$${VARNAME}"` with `SECRETFILE=${!VARNAME}, etc.

```
#!/bin/sh

# logic cribbed from linuxserver.io: 
# https://github.com/linuxserver/docker-baseimage-ubuntu/blob/bionic/root/etc/cont-init.d/01-envfile

# iterate over environmental variables
# if variable ends in "__FILE"
for FULLVAR in $(env | grep "^.*__FILE="); do
    # trim "=..." from variable name
    VARNAME=$(echo $FULLVAR | sed "s/=.*//g")
    echo "[secret-init] Evaluating ${VARNAME}"

    # set SECRETFILE to the contents of the variable
    # Use 'eval hack' for indirect expansion in sh: https://unix.stackexchange.com/questions/111618/indirect-variable-expansion-in-posix-as-done-in-bash
    # WARNING: It's not foolproof is an arbitrary command injection vulnerability 
    eval SECRETFILE="\$${VARNAME}"

    # echo "[secret-init] Setting SECRETFILE to ${SECRETFILE} ..."  # DEBUG - rm for prod!
    
    # if SECRETFILE exists
    if [[ -f ${SECRETFILE} ]]; then
        # strip the appended "__FILE" from environmental variable name
        STRIPVAR=$(echo $VARNAME | sed "s/__FILE//g")
        # echo "[secret-init] Set STRIPVAR to ${STRIPVAR}"  # DEBUG - rm for prod!

        # set value to contents of secretfile
        eval ${STRIPVAR}=$(cat "${SECRETFILE}")
        # echo "[secret_init] Set ${STRIPVAR} to $(eval echo \$${STRIPVAR})"  # DEBUG - rm for prod!
        
        export "${STRIPVAR}"
        echo "[secret-init] Success! ${STRIPVAR} set from ${VARNAME}"
        
    else
        echo "[secret-init] ERROR: Cannot find secret in ${VARNAME}"
    fi
done
```

**Comment by dominictayloruk** [comment]
I've just tested the latest version 10.5.8 and run a fresh container with secrets injected and they have created the database with the values i entered to the secret.

The bit needed for Kubernetes in the yaml:
```
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: this-is-the-secret-name
```


It should also work in swarm and most other orchestration systems.

BTW I'm using this on both Ubuntu & Alpine hosts running k3s 1.20.6 on amd64/armhf/arm64
