### ISSUE TITLE
Doesn't start since update

### ISSUE THREAD

**Issue by tadly** [yobasystems/alpine-mariadb#9]
Getting this while starting.
```/usr/bin/mysqld: Can't read dir of '/etc/mysql/conf.d/' (Errcode: 2 "No such file or directory")```

This is how I test.
```yaml
services:
  test-db:
    container_name: test-db
    image: yobasystems/alpine-mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
    restart: always
```
